import MyContextProvider from "@/lib/MyContextProvider";
import SessionProviderForNextAuth from "@/nextAuth/SessionProviderForNextAuth";
import Providers from "@/Providers/Providers";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Henrikbutz's Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
      >
        <MyContextProvider>
          <SessionProviderForNextAuth>
            <Providers>
              <Toaster richColors />
              {children}
            </Providers>
          </SessionProviderForNextAuth>
        </MyContextProvider>
      </body>
    </html>
  );
}
